# SOPHIA AI System - Pulumi ESC Environment Configuration
# This file defines the environment configuration for Pulumi ESC (Encrypted Secrets Configuration)

name: sophia-esc
description: SOPHIA AI System Encrypted Secrets Configuration
organization: payready

# Environment configuration
environments:
  - name: development
    description: Development environment
    tags:
      environment: development
      project: sophia
    
  - name: staging
    description: Staging environment
    tags:
      environment: staging
      project: sophia
    
  - name: production
    description: Production environment
    tags:
      environment: production
      project: sophia

# Secret groups
secretGroups:
  - name: api-keys
    description: API keys for external services
    environments:
      - development
      - staging
      - production
  
  - name: database-credentials
    description: Database credentials
    environments:
      - development
      - staging
      - production
  
  - name: security-tokens
    description: Security tokens and secrets
    environments:
      - development
      - staging
      - production
  
  - name: integration-credentials
    description: Credentials for integrated services
    environments:
      - development
      - staging
      - production
  
  - name: infrastructure-credentials
    description: Credentials for infrastructure services
    environments:
      - development
      - staging
      - production

# Secret mappings
secretMappings:
  # API Keys
  - name: OPENAI_API_KEY
    description: OpenAI API Key
    secretGroup: api-keys
    environmentVariableName: OPENAI_API_KEY
  
  - name: PINECONE_API_KEY
    description: Pinecone API Key
    secretGroup: api-keys
    environmentVariableName: PINECONE_API_KEY
  
  - name: WEAVIATE_API_KEY
    description: Weaviate API Key
    secretGroup: api-keys
    environmentVariableName: WEAVIATE_API_KEY
  
  - name: ANTHROPIC_API_KEY
    description: Anthropic API Key
    secretGroup: api-keys
    environmentVariableName: ANTHROPIC_API_KEY
  
  - name: ESTUARY_API_TOKEN
    description: Estuary Flow API Token
    secretGroup: api-keys
    environmentVariableName: ESTUARY_API_TOKEN
  
  - name: ESTUARY_ACCESS_TOKEN
    description: Estuary Flow Access Token
    secretGroup: api-keys
    environmentVariableName: ESTUARY_ACCESS_TOKEN
  
  - name: ELEVEN_LABS_API_KEY
    description: Eleven Labs API Key
    secretGroup: api-keys
    environmentVariableName: ELEVEN_LABS_API_KEY
  
  - name: VENICE_AI_API_KEY
    description: Venice.ai API Key
    secretGroup: api-keys
    environmentVariableName: VENICE_AI_API_KEY
  
  - name: CREW_API_TOKEN
    description: CrewAI API Token
    secretGroup: api-keys
    environmentVariableName: CREW_API_TOKEN
  
  # Database Credentials
  - name: POSTGRES_PASSWORD
    description: PostgreSQL Password
    secretGroup: database-credentials
    environmentVariableName: POSTGRES_PASSWORD
  
  - name: REDIS_PASSWORD
    description: Redis Password
    secretGroup: database-credentials
    environmentVariableName: REDIS_PASSWORD
  
  - name: SNOWFLAKE_ACCOUNT
    description: Snowflake Account
    secretGroup: database-credentials
    environmentVariableName: SNOWFLAKE_ACCOUNT
  
  - name: SNOWFLAKE_USER
    description: Snowflake User
    secretGroup: database-credentials
    environmentVariableName: SNOWFLAKE_USER
  
  - name: SNOWFLAKE_ROLE
    description: Snowflake Role
    secretGroup: database-credentials
    environmentVariableName: SNOWFLAKE_ROLE
  
  - name: SNOWFLAKE_ACCOUNT_URL
    description: Snowflake Account URL
    secretGroup: database-credentials
    environmentVariableName: SNOWFLAKE_ACCOUNT_URL
  
  - name: SNOWFLAKE_ACCOUNT_IDENTIFIER
    description: Snowflake Account Identifier
    secretGroup: database-credentials
    environmentVariableName: SNOWFLAKE_ACCOUNT_IDENTIFIER
  
  - name: SNOWFLAKE_DATA_SHARING_ACCOUNT_IDENTIFIER
    description: Snowflake Data Sharing Account Identifier
    secretGroup: database-credentials
    environmentVariableName: SNOWFLAKE_DATA_SHARING_ACCOUNT_IDENTIFIER
  
  - name: SNOWFLAKE_ORGANIZATION_NAME
    description: Snowflake Organization Name
    secretGroup: database-credentials
    environmentVariableName: SNOWFLAKE_ORGANIZATION_NAME
  
  - name: SNOWFLAKE_ACCOUNT_NAME
    description: Snowflake Account Name
    secretGroup: database-credentials
    environmentVariableName: SNOWFLAKE_ACCOUNT_NAME
  
  - name: SNOWFLAKE_ACCOUNT_LOCATOR
    description: Snowflake Account Locator
    secretGroup: database-credentials
    environmentVariableName: SNOWFLAKE_ACCOUNT_LOCATOR
  
  - name: SNOWFLAKE_CLOUD_PLATFORM
    description: Snowflake Cloud Platform
    secretGroup: database-credentials
    environmentVariableName: SNOWFLAKE_CLOUD_PLATFORM
  
  # Security Tokens
  - name: JWT_SECRET
    description: JWT Secret Key
    secretGroup: security-tokens
    environmentVariableName: JWT_SECRET
  
  - name: SLACK_SIGNING_SECRET
    description: Slack Signing Secret
    secretGroup: security-tokens
    environmentVariableName: SLACK_SIGNING_SECRET
  
  # Integration Credentials
  - name: HUBSPOT_API_KEY
    description: HubSpot API Key
    secretGroup: integration-credentials
    environmentVariableName: HUBSPOT_API_KEY
  
  - name: HUBSPOT_CLIENT_SECRET
    description: HubSpot Client Secret
    secretGroup: integration-credentials
    environmentVariableName: HUBSPOT_CLIENT_SECRET
  
  - name: SALESFORCE_ACCESS_TOKEN
    description: Salesforce Access Token
    secretGroup: integration-credentials
    environmentVariableName: SALESFORCE_ACCESS_TOKEN
  
  - name: GONG_ACCESS_KEY
    description: Gong Access Key
    secretGroup: integration-credentials
    environmentVariableName: GONG_ACCESS_KEY
  
  - name: GONG_ACCESS_KEY_SECRET
    description: Gong Access Key Secret
    secretGroup: integration-credentials
    environmentVariableName: GONG_ACCESS_KEY_SECRET
  
  - name: GONG_CLIENT_SECRET
    description: Gong Client Secret
    secretGroup: integration-credentials
    environmentVariableName: GONG_CLIENT_SECRET
  
  - name: GONG_CLIENT_ACCESS_KEY
    description: Gong Client Access Key
    secretGroup: integration-credentials
    environmentVariableName: GONG_CLIENT_ACCESS_KEY
  
  - name: GONG_BASE_URL
    description: Gong Base URL
    secretGroup: integration-credentials
    environmentVariableName: GONG_BASE_URL
  
  - name: SLACK_CLIENT_ID
    description: Slack Client ID
    secretGroup: integration-credentials
    environmentVariableName: SLACK_CLIENT_ID
  
  - name: SLACK_CLIENT_SECRET
    description: Slack Client Secret
    secretGroup: integration-credentials
    environmentVariableName: SLACK_CLIENT_SECRET
  
  - name: SLACK_SIGNING_SECRET
    description: Slack Signing Secret
    secretGroup: integration-credentials
    environmentVariableName: SLACK_SIGNING_SECRET
  
  - name: SLACK_BOT_TOKEN
    description: Slack Bot Token
    secretGroup: integration-credentials
    environmentVariableName: SLACK_BOT_TOKEN
  
  - name: SLACK_APP_TOKEN
    description: Slack App Token
    secretGroup: integration-credentials
    environmentVariableName: SLACK_APP_TOKEN
  
  - name: SLACK_REFRESH_TOKEN
    description: Slack Refresh Token
    secretGroup: integration-credentials
    environmentVariableName: SLACK_REFRESH_TOKEN
  
  - name: SLACK_SOCKET_TOKEN
    description: Slack Socket Token
    secretGroup: integration-credentials
    environmentVariableName: SLACK_SOCKET_TOKEN
  
  - name: SLACK_APP_TOKEN_2
    description: Slack App Token 2
    secretGroup: integration-credentials
    environmentVariableName: SLACK_APP_TOKEN_2
  
  # Infrastructure Credentials
  - name: AWS_ACCESS_KEY_ID
    description: AWS Access Key ID
    secretGroup: infrastructure-credentials
    environmentVariableName: AWS_ACCESS_KEY_ID
  
  - name: AWS_SECRET_ACCESS_KEY
    description: AWS Secret Access Key
    secretGroup: infrastructure-credentials
    environmentVariableName: AWS_SECRET_ACCESS_KEY
  
  - name: PULUMI_ACCESS_TOKEN
    description: Pulumi Access Token
    secretGroup: infrastructure-credentials
    environmentVariableName: PULUMI_ACCESS_TOKEN
  
  - name: DOCKERHUB_TOKEN
    description: Docker Hub Token
    secretGroup: infrastructure-credentials
    environmentVariableName: DOCKERHUB_TOKEN

# Access policies
accessPolicies:
  - name: admin-access
    description: Full access to all secrets
    secretGroups:
      - api-keys
      - database-credentials
      - security-tokens
      - integration-credentials
      - infrastructure-credentials
    environments:
      - development
      - staging
      - production
    identities:
      - type: user
        name: admin@payready.com
      - type: user
        name: musillynnl@gmail.com
  
  - name: developer-access
    description: Access to development secrets only
    secretGroups:
      - api-keys
      - database-credentials
      - security-tokens
      - integration-credentials
    environments:
      - development
    identities:
      - type: user
        name: developer@payready.com
  
  - name: ci-cd-access
    description: Access for CI/CD pipelines
    secretGroups:
      - api-keys
      - database-credentials
      - security-tokens
      - integration-credentials
      - infrastructure-credentials
    environments:
      - development
      - staging
      - production
    identities:
      - type: github
        name: payready/sophia
      - type: github
        name: ai-cherry/sophia
