[tool.bandit]
exclude_dirs = ["tests", "venv", "sophia_venv", "infrastructure/esc"]

[tool.ruff]
line-length = 88
select = ["E", "F", "W", "I", "N", "D"]
ignore = ["D100", "D101", "D102", "D103", "D104", "D105", "D107"]

[tool.ruff.pydocstyle]
convention = "google"
