name: sophia-ai
runtime: python
description: The infrastructure for the Sophia AI platform.
config:
  - aws:region
  - kubeconfig
# Associate this Pulumi project with our central ESC environment.
# This ensures that all secrets and configurations are automatically
# available to our Pulumi programs without needing to specify them manually.
environment:
  - scoobyjava-org/default/sophia-ai-production
