jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Pulumi
      run: curl -fsSL https://get.pulumi.com | sh && echo '$HOME/.pulumi/bin' >> $GITHUB_PATH
    - env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GONG_API_KEY: ${{ secrets.GONG_API_KEY }}
        GONG_CLIENT_SECRET: ${{ secrets.GONG_CLIENT_SECRET }}
        HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_API_KEY }}
        LAMBDA_LABS_API_KEY: ${{ secrets.LAMBDA_LABS_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PULUMI_ORG: ${{ secrets.PULUMI_ORG }}
        SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
      name: Deploy Infrastructure
      run: python scripts/deploy_complete_system.py
name: Deploy with Organization Secrets
'on':
  push:
    branches:
    - main
  workflow_dispatch: {}
