name: Secret Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan for secrets
        uses: zricethezav/gitleaks-action@v2
        with:
          args: "--verbose"
