name: Synchronize Secrets

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      direction:
        description: 'Synchronization direction'
        required: true
        default: 'github-to-pulumi'
        type: choice
        options:
          - github-to-pulumi
          - pulumi-to-github
          - bidirectional
      dry_run:
        description: 'Dry run (no actual changes)'
        required: false
        default: false
        type: boolean

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pulumi
      
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || apt install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
      
      - name: Login to GitHub CLI
        run: |
          echo "${{ secrets.GH_TOKEN }}" > gh_token.txt
          gh auth login --with-token < gh_token.txt
          rm gh_token.txt
      
      - name: Login to Pulumi
        run: |
          pulumi login --token ${{ secrets.PULUMI_ACCESS_TOKEN }}
      
      - name: Determine synchronization direction
        id: direction
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "direction=${{ github.event.inputs.direction }}" >> $GITHUB_OUTPUT
            echo "dry_run=${{ github.event.inputs.dry_run }}" >> $GITHUB_OUTPUT
          else
            echo "direction=github-to-pulumi" >> $GITHUB_OUTPUT
            echo "dry_run=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Synchronize secrets
        run: |
          DIRECTION="${{ steps.direction.outputs.direction }}"
          DRY_RUN="${{ steps.direction.outputs.dry_run }}"
          
          DRY_RUN_ARG=""
          if [ "$DRY_RUN" == "true" ]; then
            DRY_RUN_ARG="--dry-run"
          fi
          
          bash ./infrastructure/esc/sync_secrets_ci.sh \
            --github-org ai-cherry \
            --pulumi-org ai-cherry \
            --pulumi-env sophia-production \
            --direction $DIRECTION \
            --output sync_results.json \
            $DRY_RUN_ARG
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: sync-results
          path: sync_results.json
          retention-days: 7

